apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodebackend
  template:
    metadata:
      labels:
        app: nodebackend
    spec:
      containers:
      - name: backendapp
        image: raguyazhin/node-backend-app:1.0.0
        ports:
        - containerPort: 5000
        